### ISSUE TITLE
List /= Lists module discrepancy

### ISSUE THREAD

**Issue by OvermindDL1** [debois/elm-mdl#149]
The `Material.List` module is `List`, however everything about the Demo from the title to the breadcrumb to the tab to everything else including the documentation link (which does not work because of this)  refers to `Lists` instead of `List`.  Unsure which way it was originally wanted to be named...  List makes more sense to me though?

**Comment by debois** [comment]
Mostly historical accident, but I kind of like it: Demo pages have titles etc in plural, because they demonstrate how to use, eg., lists in your application, usually with several examples.

The demo is not entirely consistent about it, though, and I'd love a PR bringing concurrency, either by making everything singular or everything plural :)
The source 

The demo is not entirely consistent about it
