### ISSUE TITLE
Snackbar interface

### ISSUE THREAD

**Issue by OvermindDL1** [debois/elm-mdl#154]
Curious why the snackbar interface is as it is?  The Snackbar.add function returns its own model and command instead of dispatching to its own internal message handler, and you have to wrap its messages.  Is it just due to the fact that it is an older design?

**Comment by debois** [comment]
Partially. 

Snackbar model needs to contain parent messages, and so must have type `Model msg`. If Snackbar had parts support, that'd overflow into `Material.Model msg`. Users wanting to instantiate this to their particular messages now must have their `Model` and `Msg` in the same file, which they disliked. Having `Material.Model` parametric in `msg` also seemed to trigger type inference errors. I decided, since you're likely to have only one snackbar anyway, to drop Parts support for it. 

I'd take a PR improving it?
