### ISSUE TITLE
Dialogs can only open on DOM events

### ISSUE THREAD

**Issue by dannyob** [debois/elm-mdl#157]
Currently dialogs will only open and close in response to a DOM events (see Material.Dialog.openOn, Material.Dialog.closeOn).

It would be useful to be able to have a command within Elm to do this (for instance, when we detect an error and want to display it.)

**Comment by debois** [comment]
We should do this. 

The current implementation tries desperately to follow Google's via their [polyfill](https://github.com/GoogleChrome/dialog-polyfill). The result doesn't sit very well with elm, relying on semi-illicit JS hacks.

I see two ways forward:

1. Re-implement the dialog polyfill's JS bits in elm. I looked at this briefly, and it's unclear to me if this is viable. 
2. Implement "something like" that polyfill, not relying slavishly on the Google polyfill. Eg, re-purpose the [bootstrap dialog mechanics](https://github.com/twbs/bootstrap/blob/master/js/modal.js) (but obviously using MDL styling). 

I'm leaning towards (2), in part because @krisajenkins already [ported Bootstrap dialogs] independently. Starting off his implementation might be a good way forward.

**Comment by OvermindDL1** [comment]
2 makes the most sense anyway, have full control then.

**Comment by debois** [comment]
A third option would be to keep the current implementation, but require the user to add a port and some custom javascript to his project. I'm not sure I like this, but I wanted to mention the option.

**Comment by OvermindDL1** [comment]
I do that quite a bit in my Helpers library, the user specifies callback ports and the `String` name of those are given to the calling function.  I do not like it, but hard to do better in Elm.  >.>

**Comment by GoldbergGLG** [comment]
The [Html](http://package.elm-lang.org/packages/elm-lang/html/2.0.0/Html) package should eventually have `dialog` right (as in `<dialog>`)?  Then it could be built off of that?  Maybe a bad approach, but it'd be cool if it took care of the polyfil as well.

**Comment by zagaberoo** [comment]
This issue has also affected my code.  As it stands, there doesn't seem to be a good way for me to refresh the current time via a command *before* displaying the dialog without some sort of unfortunate hackery.  Currently the best I can do is have the button both issue the command and display the dialog, which naturally causes a little flicker.

**Comment by SidneyNemzer** [comment]
Is there a reason that the library has to interact with the dialog element via JavaScript? The spec allows dialogs to be shown or hidden using the element's attributes, which Elm can set via the Html package.

https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element
