### ISSUE TITLE
Multiple Layout tabs simultaneously selected 

### ISSUE THREAD

**Issue by pinx** [debois/elm-mdl#167]
Probably a timing issue. When I tap around on the tabs row, sometimes two tabs remain highlighted. Maybe a ripple effect is not running to its end.

**Comment by OvermindDL1** [comment]
I've noticed the same thing randomly on desktop as well on the demo.  Unable to reliably reproduce, but it definitely happens.

**Comment by debois** [comment]
I can't reproduce this in a few tries, but that's maybe not suprising.  

@OvermindDL1, if you see this again, could you use the inspector and produce a screen-shot where I can see the bug, and the DOM elements (especially classes and css) for the tabs that are simultaneously highlighted?

**Comment by OvermindDL1** [comment]
Hah, speaking of which it just happened randomly again on Chrome on my desktop at work, only one left showing the ripple but sometimes other oddities happen:  https://overminddl1.com/screenshots/work/Toolbar-misselected-ripple.png
![Example bug](https://overminddl1.com/screenshots/work/Toolbar-misselected-ripple.png)

The Footers was selected, I clicked Dialog and quickly went to Footers (the ripple animation was still playing), the ripple on Dialog ended up like that and the ripple on Footers I do not think played (it acted like plain button, it might have rippled but I do not recall seeing).

I was very careful to not mouse anywhere near it (mousing over the thing with this bug causes it 'reset'), opened the DOM inspector and drilled down to it.

Here is the DOM of the Dialog button on the toolbar (formatted by me for readability):
```html
<a class="mdl-layout__tab">
  Dialog
  <span class="mdl-layout__tab-ripple-container">
    <span class="mdl-ripple is-animating is-visible" style="width: 226px; height: 226px; transform: translate(-50%, -50%) translate(88px, 26px);">
    </span>
  </span>
</a>
```

Here is the currently selected 'Footer' button:
```html
<a class="mdl-layout__tab is-active">
  Footers
  <span class="mdl-layout__tab-ripple-container">
    <span class="mdl-ripple is-animating" style="width: 253px; height: 253px; transform: translate(-50%, -50%) translate(102px, 28px);">
    </span>
  </span>
</a>
```

And just for a comparison here is the not-yet touched 'Elevation' button between them:
```html
<a class="mdl-layout__tab">
  Elevation
  <span class="mdl-layout__tab-ripple-container">
    <span class="mdl-ripple is-animating" style="width: 268px; height: 268px; transform: translate(-50%, -50%) translate(35px, 27px);">
    </span>
  </span>
</a>
```

So yeah, the 'is-visible' did not seem to get cleared, and since I did not notice the ripple on Footers then that might be related.

I now changed to a tab other than Dialog and Footers (Cards) and Dialog remained with the ripple showing, Cards **did** have a ripple.
And of course mousing over (then off) the Dialog button tab reset it and it worked fine again.
