### ISSUE TITLE
Cannot set tabindex on Textfield

### ISSUE THREAD

**Issue by aforemny** [debois/elm-mdl#191]
I cannot set the `Html.attributes.tabindex` on a Textfield, because any options are set on the containing `div`. Or is there a way that I am missing?

I suppose we should expose a `Textfield.tabindex : Int -> Textfield.Property m` function.

**Comment by debois** [comment]
Yes. 

Just to be sure, `style` won't help, somehow?
http://package.elm-lang.org/packages/debois/elm-mdl/7.4.0/Material-Textfield#style

Otherwise, for v7, we should just add this. 

For master, it would be good to find a way to avoid wrapping so many attributes for `input` elements in Options. I don't how, though: we can't have users messing up our event handlers.

**Comment by OvermindDL1** [comment]
Maybe it would be better to tag things a certain way?  Like say Textfield could have another type in it like:
```elm
type Nodes
  = OuterContainer
  | InnerTextfield
```
Or so, then you could decorate the calls where it matters, like `Options.cs Textfield.OuterContainer "blah"` or `Options.cs Textfield.InnerTextfield "blah"`.  If the entirety of Options followed that then it would work well.  You could have an Options.defaultNode as a fill-in for ones that have no thing to attach to or just want to attach to the default node whatever it may be, however that would probably require the above 'Textfield.Nodes` to come from a base type or something, or be a function call to build a specific value (or heck, just return an integer index of the field?).

**Comment by debois** [comment]
Can you even set `tabindex` through CSS?

**Comment by OvermindDL1** [comment]
> Can you even set tabindex through CSS?

Sadly no...  It has to be on the element itself.

**Comment by debois** [comment]
Closing this; it'll be fixed by #213.
