### ISSUE TITLE
Options.attribute is too restrictive

### ISSUE THREAD

**Issue by aforemny** [debois/elm-mdl#192]
Options.attribute is of type `Property () m`. It should be of type `Property a m`, so that it can actually be used on material components.

Possibly, `Style` should generally be `Property a m` instead of `Property () m`.

**Comment by debois** [comment]
It was made that way to prevent users overriding Material component event handlers. E.g., Textfield needs to handle Blur; if users install an 'onBlur` handler using `attribute`, Textfield breaks. I saw this happen a couple of times.

The `Style` type is there so that Options can be used on HTML.* elements; `attribute` so that on HTML.* elements you really can do whatever you want.


@vipentti is working on a general solution for events in #179.

Is there a particular attribute that's sorely missing?

**Comment by domenkozar** [comment]
I've found out you can't set `title` attribute on components due to this. Not the end of the world, as you can wrap the component in another element and set it there.

**Comment by OvermindDL1** [comment]
Is there really no way to introspect into Attributes and combine, say, blur handlers into your own and such?  Could then go back to using Html.attributes then...

**Comment by vipentti** [comment]
Unfortunately I don't think there is currently a way to access any `Html.Attribute` to perform any operations on them.

**Comment by OvermindDL1** [comment]
There is... but it requires native code currently as far as I've been able to find.  Maybe a PR should be sent to elm-lang/elm-html to add the Attribute types as exposed?  Backwards compatible so they may take it.

**Comment by debois** [comment]
Closing this in favor of #208. (Should have continued here instead, but I already re-directed other issues to #208. Sorry!)
