### ISSUE TITLE
Textfield UI does not reflect changes to the model

### ISSUE THREAD

**Issue by ChetHarrison** [debois/elm-mdl#255]
I have a form that I can dynamically add or delete paragraphs of text. The model contains an "intro" attribute that is a List of Strings for each paragraph. In the following video, I am deleting paragraphs. If you look at the log statements you have and "old model intro" and "new model intro". I have added an "A", "B" and "C" paragraph. When I try to delete the "A" the logs confirm that the model is accurately being updated but the UI is deleting the "C" Textfield. When I try and delete "A" again it deletes the "B" Textfield instead.

Any thoughts on what is happening?

[VIDEO EXAMPLE](https://cl.ly/3g1I1q2A1k3v)

**Comment by OvermindDL1** [comment]
Because you need to use keyed nodes for the containers of the textedits (or make containers that are keyed).  This is an elm design issue, not possible for elm-mdl to work around, but easy enough to fix once you learn about elm rendering oddities (which exist for efficiency reasons combined with that textboxes in browsers cannot have easily updated values).

**Comment by ChetHarrison** [comment]
Thanks for the insight. If I am understanding your explanation does the fix lie in a better understanding of the v-dom or the keyed mdl "parts" module?

**Comment by OvermindDL1** [comment]
Better understanding of the Elm v-dom itself.  The v-dom has a few quirks (that exist for a good reason, but still quirks), and this exact one is the most common one to trip up people.  You'll see the same issue if using raw elm without elm-mdl.  :-)

Let me see if I can say something that makes sense succinctly.  ^.^

When you delete the node then elm checks the contents of things to see what needs to be updated.
However in textfields the DOM completely controls that, updating the defaultValue or text will not update the information in the DOM itself when the vdom does it, and the vdom does not know that it needs to destroy that node so rather it just 'updates the differences' as far as it can see, thus destroying the bottom one since the overall list was shorter.  You can work around it in two ways, either by storing all the text from every textfield all the time and updating on every update via a value attribute (this is a bad user experience as it keeps causing the cursor to jump to the end, same issue you have in javascript itself), or you use the v-dom way of handling it by using key nodes.  Have each of the parts have its own key, when one is deleted then that entire keyed dom element is entirely deleted unstead of doing a deep-diff/patch.

If you show code then we/I can show you where the keyed elements should go.  :-)

**Comment by ChetHarrison** [comment]
Wow! That would have taken me weeks to figure out! Thanks for the kind offer. I am heading out to dinner right now. But I will whip up some gists and reach out to you on Monday. Have a great weekend 🍸
