### ISSUE TITLE
Textfield.on and Textfield.style compile errors

### ISSUE THREAD

**Issue by kittykatattack** [debois/elm-mdl#266]
Hi,

I'm just busy upgrading to the current version of elm-mdl and have received the following compile errors:
```

Cannot find variable `Textfield.on`.

938|                     , Textfield.on "input" (Json.map msg targetValue)
                           ^^^^^^^^^^^^
`Textfield` does not expose `on`. 

Cannot find variable `Textfield.style`.

940|                     , Textfield.style
                           ^^^^^^^^^^^^^^^
`Textfield` does not expose `style`. 
```
I didn't notice anything in the migration guide or the docs about how to upgrade these from v7.
Can anyone suggest a solution?

Thanks!

**Comment by kittykatattack** [comment]
Thanks, I have tried that, and `Options.onClick` works for buttons, but there doesn't seem to be an `Options.on` or `Options.style`

**Comment by debois** [comment]
There should be an `Option.on`, see [here](http://package.elm-lang.org/packages/debois/elm-mdl/8.1.0/Material-Options#on)?

Instead of `Textfield.style`, use `Options.input`, see [here](http://package.elm-lang.org/packages/debois/elm-mdl/8.1.0/Material-Options#input)—you may want to look at the preceding comments on that page. I've updated the migration guide to make this clear. 

@kittykatattack: I'm closing this for now. Feel free to re-open if the above doesn't help!

**Comment by kittykatattack** [comment]
@debois Thanks so much Søren, it works! 
Brilliant work on elm-mdl 😄
