### ISSUE TITLE
[QUESTION] A separate model for every component or not?

### ISSUE THREAD

**Issue by not-much-io** [debois/elm-mdl#58]
In Component.elm:

`
type alias Model = 
  { count : Int
  , mdl : Material.Model 
      -- Boilerplate: mdl is the Model store for any and all MDL components you need. 
  }
`

"mdl is the Model store for **any and all MDL components** you need." - Okay, nice so I only need one?

But in Component-TEA.elm:

`
type alias Model = 
  { count : Int
  , increaseButtonModel : Button.Model
  , resetButtonModel : Button.Model
  }
`

Eee, so do I need to prepare a separate model for every component I add? Don't get me wrong, hyped about the lib even with the boilerplate, but there seems to be a difference in the two examples.

**Comment by debois** [comment]
That's a reasonable question.

Short answer: No, you need only one model. Forget about Component-TEA.elm and look at Component.elm instead.

Long answer: most elm-mdl component comprises both a vanilla TEA-component and a specially-typed TEA component called a "Part". The latter is special in that it knows how to retrieve its model from the single model you mention above. 

Component.elm and Component-TEA.elm are actually two different implementations of exactly the same app: the former using Parts, the latter in vanilla TEA. Obviously, the vanilla TEA implementation needs to host the state of its GUI components in the model. The Parts implementation need only the one Mdl field as a common container for the state of all components used in the program.

We recommend you use Parts rather than vanilla TEA, because parts are /much/ more convenient when experimenting with which controls you want in your app.

**Comment by not-much-io** [comment]
Got it, thanks! For those who might read this: https://github.com/debois/elm-parts

**Comment by debois** [comment]
Welcome!

I'll be interested to hear more of your experience with elm-mdl when you've had a chance to use it some more—maybe look me up on the elm-slack (@debois) in a couple of weeks?

**Comment by not-much-io** [comment]
Sure, will do.
