### ISSUE TITLE
Implement Slider component

### ISSUE THREAD

**Issue by debois** [debois/elm-mdl#69]
See [here](https://getmdl.io/components/index.html#sliders-section).  Some javascript [involved](https://github.com/google/material-design-lite/blob/master/src/slider/slider.js).

**Comment by vipentti** [comment]
I did some research into possibly implementing a `Slider` component. The component itself is pretty simple to implement. However, there is one part of the MDL implementation that is currently very difficult, if not impossible to implement in Elm.

https://github.com/google/material-design-lite/blob/mdl-1.x/src/slider/slider.js#L106-L123

What this does is allow the user to click on the `container` element and start dragging, otherwise on Firefox the user has to click on the very narrow slider itself.

**Comment by aforemny** [comment]
@vipentti: You are right, the very same thing is not possible in Elm. However, you do not need to be as faithful to the JS implementation. I think you could just handle the event on the container. Or am I missing something?

**Comment by vipentti** [comment]
Let me try and explain how I understand it and maybe there indeed is a simpler way to solve the problem.

So, when you try and create `Slider` component using regular MDL it actually wraps it in the following HTML structure

```html
<div class="mdl-slider__container">
    <input class="mdl-slider mdl-js-slider is-lowest-value is-upgraded" 
           type="range" min="0" max="100" value="0" tabindex="0" 
           data-upgraded=",MaterialSlider">
    <div class="mdl-slider__background-flex">
        <div class="mdl-slider__background-lower" style="flex: 0 1 0%;"></div>
        <div class="mdl-slider__background-upper" style="flex: 1 1 0%;"></div>
    </div>
</div>
```

Which actually is simple enough to implement even in Elm. The problem however is that the `input` is only 2px tall, meaning to actually start changing the value you have to hit the small area. This is not really a problem on Chrome, on Firefox without handling the `mousedown` event on the `mdl-slider__container` and `re-dispatching` it to the `input` the drag target is really small.

Now, I think you could possibly handle the mousedown and drag events on the container itself in Elm and then calculate the `input` value manually. However, getting this to `emit` some sort of change event back to the user is something I'm not sure how to properly implement.

Currently what I have for the API is:

```elm
import Material.Slider as Slider 

slider : Model -> Html Msg
slider model = 
    Slider.render Mdl [0] model.mdl
        [ Slider.onChange (Slider 0)
        , Slider.value (get 0 model.values)
        ]
        []
```

Which works pretty well on Chrome, on Firefox without performing some additional steps it does not really work though.

Open to ideas and feedback.

**Comment by aforemny** [comment]
What do you mean by emitting a change event to the user? I am assuming that you want to handle events on the input, say `Change`. Additionally, to solve the issue in Firefox, you want to handle events on the container, say `Change'`. The user could listen to both `Change` and `Change'` events in their `update` function. Is this what you mean by emitting?

If you do not like the fact that the user has to watch both events `Change` and `Change'`, can't you fire a `RealChange` event in both cases, ie.

> update msg model =
>   case msg of
>     Change -> model ! [ Material.Helpers.fx RealChange ]
>     Change' -> model ! [ Material.Helpers.fx RealChange ]

You might also consider only handling events on container as this might suffice, also in Chrome.

Another approach would be to pass information from `Config.onChange` to the `Change` (or `Change'`) event and fire that using effects as above.

It might be that there is something `elm-parts`-y thing involved here that I do not get, as I am not very familiar with `elm-parts`, unfortunately. :)

I think it would be helpful to discuss some real code. In case you have a somewhat working branch already - that would not be too much effort for you to publish - I would appreciate it.

**Comment by vipentti** [comment]
Hey! 

I pushed my development version, which is very very minimal and simple.

Component: https://github.com/vipentti/elm-mdl/blob/slider-component/src/Material/Slider.elm
Demo here: https://github.com/vipentti/elm-mdl/blob/slider-component/demo/Demo/Slider.elm

The actual implementation is pretty simple and small, and it works pretty well on Chrome as is, on Firefox it just requires you to click on the tiny 2px tall input to start draggin. Other than that it works reasonably well.

Does not work on IE, needs some conditional logic.

**Comment by aforemny** [comment]
Pretty unrelated to what I suggested first, but what about setting

    Html.style [ ("padding", "8px 0") ]

on the `input` element?

**Comment by vipentti** [comment]
Hey,

I can prepare the current implementation for PR. Going to clean it up and document and whatnot, I will also try the padding.

Regarding IE, it is addressed in the MDL implementation as well.

https://github.com/google/material-design-lite/blob/mdl-1.x/src/slider/_slider.scss#L343-L351
https://github.com/google/material-design-lite/blob/mdl-1.x/src/slider/slider.js#L141-L146
https://github.com/google/material-design-lite/blob/mdl-1.x/src/slider/slider.js#L193-L201

I believe it is due to IE not supporting Flexboxes properly. The slider does work on IE11 it just needs a workaround. For some reason it does not work properly on [Edge](https://github.com/google/material-design-lite/issues/1625) though.

I don't know if there is currently a way to detect the browser from Elm without resorting to JS.
