### ISSUE TITLE
Additional textfield attributes?

### ISSUE THREAD

**Issue by kittykatattack** [debois/elm-mdl#87]
Hello,

Is it possible to set standard elm-html attributes on MDL textfields, such as `onEnter`, `onBlur`, `onFocus`, `maxlength` and `autofocus`?

**Comment by debois** [comment]
Not presently, but it should be.

We removed the ability to install arbitrary `Html.Attributes` on elm-mdl elements because it sometimes messes up elm-mdl events, and because users kept finding ways to get in trouble with it.

The right way to go would be to implement the handlers needed like the current [`onInput` handler](https://github.com/debois/elm-mdl/blob/master/src/Material/Textfield.elm#L144,L150). Note that `onBlur` and `onFocus` would need to be implemented by `onfocusout/onfocusin` in the div containing the input.

I would look at this, but I have to prioritize Firefox breaking everything all the time. 

Would you care to submit a PR? I'd help out with any questions you may have, either here or on the elm-slack (@debois). If you spend five minutes looking at the [Textfield implementation](https://github.com/debois/elm-mdl/blob/master/src/Material/Textfield.elm), I'm sure you'll find it's something you can hack :)

**Comment by kittykatattack** [comment]
Thank you, Sir!
Unfortunately I do not yet have the skill to submit a PR, but would certainly love to help out in future as my Elm skills improve.
No worries, I can work around this for now :smile: 
Good luck with your work on Firefox (I've also had a lot problems with it recently in another JS library I  maintain.)

**Comment by debois** [comment]
Ok!

In case you change your mind (or suddenly have time on your hands, or someone else wants to have a go):

To add `maxlength` or `autofocus`, you need just mimic the `value` attribute, which is supported. See [here](https://github.com/debois/elm-mdl/blob/master/src/Material/Textfield.elm#L128-L133) and [here](https://github.com/debois/elm-mdl/blob/master/src/Material/Textfield.elm#L307-L309).

To add `on*`, see the comments above.

**Comment by debois** [comment]
Ville did this. It'll be in the next release.
